site_name: Help Me Please!!!
site_description: 自个儿的速查文档

copyright: 'Copyright &copy; since 2019 Diwen Liu'

docs_dir: notes

repo_url: https://github.com/demon90s/Help_Me_Mysql
edit_uri: "tree/master/notes"

nav:
  - About: index.md
  - C:
    - HelloWorld: C/HelloWorld.md
    - Makefile: C/Makefile.md
    - static library: C/static_library.md
    - shared library: C/shared_library.md
    - format code: C/format_code.md
    - command-line_args: C/command-line_args.md
    - debug by gdb: C/debug_by_gdb.md
    - cmake: C/cmake.md
  - C++:
    - cppman: C++/cppman.md
    - cpp thread: C++/cpp_thread.md
    - gcc/g++: C++/gcc-g++.md
    - constructor_destructor: C++/constructor_destructor.md
    - cppcheck: C++/cppcheck.md
    - valgrind: C++/valgrind.md
  - shell:
    - grammer: shell/grammer.md
    - 获取命令输出: shell/获取命令输出.md
    - 字符串操作: shell/字符串操作.md
    - 设置输出字体: shell/设置输出字体.md
    - bc: shell/bc.md
    - ln: shell/ln.md
    - 删除掉行尾^M: shell/删除掉行尾^M.md
  - Linux:
    - VirtualBox挂载新的硬盘: Linux/VirtualBox挂载新的硬盘.md
    - 修改目录或文件的权限: Linux/修改目录或文件的权限.md
    - 内网穿透: Linux/内网穿透.md
    - 设置 non-root 用户的最大打开文件数量: Linux/设置 non-root 用户的最大打开文件数量.md
    - 升级gcc: Linux/升级gcc.md
    - 通过scl启用c++11: Linux/通过scl启用c++11.md
    - 杂项问题: Linux/杂项问题.md
    - yum: Linux/yum.md
    - 工具程序: Linux/工具程序.md
    - 查看 CentOS 版本号: Linux/查看 CentOS 版本号.md
    - ftp: Linux/ftp.md
  - vim:
    - settings: vim/settings.md
    - file edit: vim/file_edit.md
    - file navigation: vim/file_navigation.md
    - shell command: vim/shell_command.md
    - window: vim/window.md
    - file buffer: vim/file_buffer.md
  - Mysql:
    - shell_scripts: Mysql/shell_scripts.md
    - 01 install: Mysql/01_install.md
    - 02 create user: Mysql/02_create_user.md
    - 03 create db: Mysql/03_create_db.md
    - 04 drop db: Mysql/04_drop_db.md
    - 05 show db: Mysql/05_show_db.md
    - 06 create table: Mysql/06_create_table.md
    - 07 drop table: Mysql/07_drop_table.md
    - 08 insert record: Mysql/08_insert_record.md
    - 09 remove record: Mysql/09_remove_record.md
    - 10 update record: Mysql/10_update_record.md
    - 11 alter table: Mysql/11_alter_table.md
    - 12 show column: Mysql/12_show_column.md
    - 13 select: Mysql/13_select.md
    - 14 mysqldump: Mysql/14_mysqldump.md
    - 15 functions: Mysql/15_functions.md
    - 16 execute_sql_in_shell: Mysql/16_execute_sql_in_shell.md
    - 17 privileges: Mysql/17_privileges.md
  - Docker:
    - docker安装: Docker/docker安装.md
    - docker: Docker/docker.md
    - docker容器数据卷: Docker/docker容器数据卷.md
    - dockerFile: Docker/dockerFile.md
  - Misc:
    - batch: Misc/batch.md
    - mkdocs使用: Misc/mkdocs使用.md
    - QT_for_develop: Misc/QT_for_develop.md
    - vs code: Misc/vs code.md
    - vs: Misc/vs.md
    - markdown: Misc/markdown.md

theme:
  name: 'material'
  logo:
    icon: 'school'
  palette:
    primary: 'blue'
    accent: 'blue'
  font:
    text: 'PT Sans'
    code: 'PT Sans'
  language: 'zh'
  feature:
    tabs: true

extra:
  search:
    language: 'en, jp'

markdown_extensions:
  - codehilite