site_name: Help Me Please!!!
site_description: 自个儿的速查文档

copyright: 'Copyright &copy; since 2019 Diwen Liu'

docs_dir: notes

repo_url: https://github.com/demon90s/Help_Me_Mysql
edit_uri: "tree/master/notes"

nav:
  - About: index.md
  - C:
    - 01 HelloWorld: C/01_HelloWorld.md
    - 02 Makefile: C/02_Makefile.md
    - 03 static library: C/03_static_library.md
    - 04 shared library: C/04_shared_library.md
    - 05 format code: C/05_format_code.md
    - 06_command-line_args: C/06_command-line_args.md
  - Mysql:
    - 01 install: Mysql/01_install.md
    - 02 create user: Mysql/02_create_user.md
    - 03 create db: Mysql/03_create_db.md
    - 04 drop db: Mysql/04_drop_db.md
    - 05 show db: Mysql/05_show_db.md
    - 06 create table: Mysql/06_create_table.md
    - 07 drop table: Mysql/07_drop_table.md
    - 08 insert record: Mysql/08_insert_record.md
    - 09 remove record: Mysql/09_remove_record.md
    - 10 update record: Mysql/10_update_record.md
    - 11 alter table: Mysql/11_alter_table.md
    - 12 show column: Mysql/12_show_column.md
    - 13 select: Mysql/13_select.md
    - 14 mysqldump: Mysql/14_mysqldump.md
    - 15 functions: Mysql/15_functions.md
    - 16 execute_sql_in_shell: Mysql/16_execute_sql_in_shell.md
    - 17 privileges: Mysql/17_privileges.md

theme:
  #name: 'material'
  name: mkdocs
  logo:
    icon: 'school'
  palette:
    #primary: 'blue'
    #accent: 'blue'
  font:
    #text: 'Open Sans'
    #code: 'Open Sans Mono'
  language: 'zh'

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.mark

google_analytics:
  - 'UA-XXXXXXXX-X'
  - 'auto'
